<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="IVF111" name="com_Milan_Test.WcomplaintsTest" tests="8" failures="1" timestamp="27 Jul 2018 21:10:22 GMT" time="433.299" errors="0">
  <testcase name="NumberOfComplaintsTest" time="83.863" classname="com_Milan_Test.WcomplaintsTest"/>
  <testcase name="SaveTheComplaintsTest" time="57.059" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- SaveTheComplaintsTest -->
  <testcase name="SaveTheComplaintsTest" time="30.411" classname="com_Milan_Test.WcomplaintsTest"/>
  <testcase name="SaveTheComplaintsTest" time="127.740" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- SaveTheComplaintsTest -->
  <testcase name="NextFollowUpTest" time="27.798" classname="com_Milan_Test.WcomplaintsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com_Milan_Test.WcomplaintsTest.NextFollowUpTest(WcomplaintsTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="55.743" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="24.399" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="26.286" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
</testsuite> <!-- com_Milan_Test.WcomplaintsTest -->
