<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="IVF111" name="com_Milan_Test.WcomplaintsTest" tests="7" failures="1" timestamp="25 Jul 2018 21:03:57 GMT" time="374.300" errors="0">
  <testcase name="NumberOfComplaintsTest" time="55.823" classname="com_Milan_Test.WcomplaintsTest"/>
  <testcase name="SaveTheComplaintsTest" time="153.516" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- SaveTheComplaintsTest -->
  <testcase name="SaveTheComplaintsTest" time="30.213" classname="com_Milan_Test.WcomplaintsTest"/>
  <testcase name="NextFollowUpTest" time="27.588" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="26.458" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="25.189" classname="com_Milan_Test.WcomplaintsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com_Milan_Test.WcomplaintsTest.NextFollowUpTest(WcomplaintsTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- NextFollowUpTest -->
  <testcase name="NextFollowUpTest" time="55.513" classname="com_Milan_Test.WcomplaintsTest">
    <skipped/>
  </testcase> <!-- NextFollowUpTest -->
</testsuite> <!-- com_Milan_Test.WcomplaintsTest -->
