<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.WVitalsTest" tests="19" failures="3" timestamp="25 Jun 2018 18:51:47 GMT" time="1022.664" errors="0">
  <testcase name="BMITest" time="54.411" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="50.367" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="53.020" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="54.572" classname="com_Milan_Test.WVitalsTest">
    <skipped/>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BMITest" time="53.897" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="53.422" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="53.208" classname="com_Milan_Test.WVitalsTest">
    <skipped/>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BPSystolicBundryValueTest" time="50.124" classname="com_Milan_Test.WVitalsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com_Milan_Test.WVitalsTest.BPSystolicBundryValueTest(WVitalsTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BMITest" time="54.741" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="52.517" classname="com_Milan_Test.WVitalsTest">
    <skipped/>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BPSystolicBundryValueTest" time="52.708" classname="com_Milan_Test.WVitalsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com_Milan_Test.WVitalsTest.BPSystolicBundryValueTest(WVitalsTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BMITest" time="54.086" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="BPSystolicBundryValueTest" time="54.623" classname="com_Milan_Test.WVitalsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com_Milan_Test.WVitalsTest.BPSystolicBundryValueTest(WVitalsTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- BPSystolicBundryValueTest -->
  <testcase name="BMITest" time="54.213" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="SaveAllVitalsValuesTest" time="54.808" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="SaveAllVitalsValuesTest" time="56.775" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="SaveAllVitalsValuesTest" time="55.395" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="SaveAllVitalsValuesTest" time="55.560" classname="com_Milan_Test.WVitalsTest"/>
  <testcase name="SaveAllVitalsValuesTest" time="54.217" classname="com_Milan_Test.WVitalsTest"/>
</testsuite> <!-- com_Milan_Test.WVitalsTest -->
