<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="IVF111" name="com_Milan_Test.WInvestigationPageTest" tests="7" failures="0" timestamp="30 May 2018 20:20:21 GMT" time="219.382" errors="1">
  <testcase name="OPUCycleTest" time="56.989" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OPUCycleTest -->
  <testcase name="OPUCycleTest" time="50.115" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OPUCycleTest -->
  <testcase name="OPUCycleTest" time="56.510" classname="com_Milan_Test.WInvestigationPageTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com_milan_POM.WInvestigationPage.OPUCycle(WInvestigationPage.java:273)
	at com_Milan_Test.WInvestigationPageTest.OPUCycleTest(WInvestigationPageTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- OPUCycleTest -->
  <testcase name="OPUCycleTest" time="55.768" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OPUCycleTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- IVFPACKAGEARTCyclecountTest -->
  <testcase name="CycleCreationTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="OUIARTSubTypesTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OUIARTSubTypesTest -->
</testsuite> <!-- com_Milan_Test.WInvestigationPageTest -->
