<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="IVF111" name="com_Milan_Test.WMenstrualHistoryTest" tests="14" failures="2" timestamp="23 May 2018 20:29:47 GMT" time="741.886" errors="0">
  <testcase name="AgeOfMenarcheRangeSartTest" time="55.617" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- AgeOfMenarcheRangeSartTest -->
  <testcase name="AgeOfMenarcheRangeSartTest" time="55.177" classname="com_Milan_Test.WMenstrualHistoryTest">
    <failure type="java.lang.AssertionError" message="8 expected:&lt;8&gt; but was:&lt;First range value is incorrect&gt;">
      <![CDATA[java.lang.AssertionError: 8 expected:<8> but was:<First range value is incorrect>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at com_Milan_Test.WMenstrualHistoryTest.AgeOfMenarcheRangeSartTest(WMenstrualHistoryTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AgeOfMenarcheRangeSartTest -->
  <testcase name="AgeOfMenarcheRangeSartTest" time="53.159" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- AgeOfMenarcheRangeSartTest -->
  <testcase name="AgeOfMenarcheRangeSartTest" time="53.000" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- AgeOfMenarcheRangeSartTest -->
  <testcase name="MenarcheRangeEndTest" time="53.448" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- MenarcheRangeEndTest -->
  <testcase name="MenarcheRangeEndTest" time="51.480" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- MenarcheRangeEndTest -->
  <testcase name="MenarcheRangeEndTest" time="53.397" classname="com_Milan_Test.WMenstrualHistoryTest">
    <skipped/>
  </testcase> <!-- MenarcheRangeEndTest -->
  <testcase name="MenarcheRangeEndTest" time="51.045" classname="com_Milan_Test.WMenstrualHistoryTest">
    <failure type="java.lang.AssertionError" message="18 expected:&lt;18&gt; but was:&lt;Last range value is incorrect&gt;">
      <![CDATA[java.lang.AssertionError: 18 expected:<18> but was:<Last range value is incorrect>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at com_Milan_Test.WMenstrualHistoryTest.MenarcheRangeEndTest(WMenstrualHistoryTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- MenarcheRangeEndTest -->
  <testcase name="LMPcalenderdateSelectionTest" time="53.517" classname="com_Milan_Test.WMenstrualHistoryTest"/>
  <testcase name="AmenorrheaTypeTest" time="53.056" classname="com_Milan_Test.WMenstrualHistoryTest"/>
  <testcase name="CycleDurationTest" time="51.164" classname="com_Milan_Test.WMenstrualHistoryTest"/>
  <testcase name="SavevaluesTest" time="51.435" classname="com_Milan_Test.WMenstrualHistoryTest"/>
  <testcase name="MenstruationTest1" time="51.629" classname="com_Milan_Test.WMenstrualHistoryTest"/>
  <testcase name="MenstrualFlowtextTest" time="54.762" classname="com_Milan_Test.WMenstrualHistoryTest"/>
</testsuite> <!-- com_Milan_Test.WMenstrualHistoryTest -->
