<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="IVF111" name="com_Milan_Test.WInvestigationPageTest" tests="10" failures="1" timestamp="23 May 2018 20:29:47 GMT" time="276.989" errors="1">
  <testcase name="CycleCreationTest" time="25.443" classname="com_Milan_Test.WInvestigationPageTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 7, Size: 7">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com_milan_POM.WInvestigationPage.Setsearchvalue(WInvestigationPage.java:67)
	at com_Milan_Test.WInvestigationPageTest.CycleCreationTest(WInvestigationPageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="24.832" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="24.492" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="24.833" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="29.541" classname="com_Milan_Test.WInvestigationPageTest">
    <failure type="java.lang.AssertionError" message="expected [7] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com_Milan_Test.WInvestigationPageTest.IVFPACKAGEARTCyclecountTest(WInvestigationPageTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IVFPACKAGEARTCyclecountTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="30.451" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- IVFPACKAGEARTCyclecountTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="29.124" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- IVFPACKAGEARTCyclecountTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="26.450" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- IVFPACKAGEARTCyclecountTest -->
  <testcase name="OUIARTSubTypesTest" time="29.203" classname="com_Milan_Test.WInvestigationPageTest"/>
  <testcase name="OPUCycleTest" time="32.620" classname="com_Milan_Test.WInvestigationPageTest"/>
</testsuite> <!-- com_Milan_Test.WInvestigationPageTest -->
