<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.CycleOverviewPageTest" tests="7" failures="1" timestamp="20 Jul 2018 20:50:58 GMT" time="610.643" errors="0">
  <testcase name="ValueInSourceofSpermOptionTest" time="92.219" classname="com_Milan_Test.CycleOverviewPageTest"/>
  <testcase name="ValueInMethodOfSemenCollectionOptionTest" time="92.010" classname="com_Milan_Test.CycleOverviewPageTest"/>
  <testcase name="ValueInProtocolTest" time="86.074" classname="com_Milan_Test.CycleOverviewPageTest">
    <failure type="java.lang.AssertionError" message="expected [Antagonist] but found []">
      <![CDATA[java.lang.AssertionError: expected [Antagonist] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.CycleOverviewPageTest.ValueInProtocolTest(CycleOverviewPageTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValueInProtocolTest -->
  <testcase name="ValueInProtocolTest" time="84.344" classname="com_Milan_Test.CycleOverviewPageTest">
    <skipped/>
  </testcase> <!-- ValueInProtocolTest -->
  <testcase name="ValueInProtocolTest" time="86.233" classname="com_Milan_Test.CycleOverviewPageTest">
    <skipped/>
  </testcase> <!-- ValueInProtocolTest -->
  <testcase name="ValueInProtocolTest" time="84.679" classname="com_Milan_Test.CycleOverviewPageTest">
    <skipped/>
  </testcase> <!-- ValueInProtocolTest -->
  <testcase name="ValueInARTTypeTest" time="85.084" classname="com_Milan_Test.CycleOverviewPageTest"/>
</testsuite> <!-- com_Milan_Test.CycleOverviewPageTest -->
