<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="IVF111" name="com_Milan_Test.WInvestigationPageTest" tests="7" failures="1" timestamp="08 Jun 2018 20:30:01 GMT" time="281.639" errors="0">
  <testcase name="CycleCreationTest" time="47.495" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="47.822" classname="com_Milan_Test.WInvestigationPageTest">
    <failure type="java.lang.AssertionError" message="expected [8] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [7]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com_Milan_Test.WInvestigationPageTest.CycleCreationTest(WInvestigationPageTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="44.972" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="CycleCreationTest" time="46.257" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="46.930" classname="com_Milan_Test.WInvestigationPageTest"/>
  <testcase name="OUIARTSubTypesTest" time="48.163" classname="com_Milan_Test.WInvestigationPageTest"/>
  <testcase name="OPUCycleTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OPUCycleTest -->
</testsuite> <!-- com_Milan_Test.WInvestigationPageTest -->
